---
title: "Text mining homework"
author: "A Hameed"
date: "28/02/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

 
```{r}
library(tidyverse)
library(janeaustenr)
library(tidytext)
```
 
# Find the most common words in both Pride & Prejudice and Sense & Sensibility.

```{r}
books <- austen_books() 
```


```{r}
books <- books %>% 
     unnest_tokens(word, text)  
 
books %>% 
   count(word, sort = TRUE)

 
```


Find the most common words in both Pride & Prejudice and Sense & Sensibility, not including stop words.

```{r}
Pride_Prej_no_stop_words <- books %>% 
    anti_join(stop_words)  

Pride_Prej_no_stop_words %>% 
   count(word, sort = TRUE)
```


Find the most common sentiment words in both Pride & Prejudice and Sense & Sensibility.

```{r}
   books %>% 
   filter(book == "Pride & Prejudice")  %>% 
   inner_join(get_sentiments("nrc")) %>% 
  filter(sentiment == "positive") %>% 
  count(word, sort = TRUE)

 
```


```{r}
#Negative:
 books %>% 
     filter(book == "Pride & Prejudice")  %>% 
     inner_join(get_sentiments("nrc")) %>% 
     filter(sentiment == "negative") %>%
   count(word, sort = TRUE)
```

```{r}
#positive Sense & Sensibility
   books %>% 
   filter(book == "Sense & Sensibility")  %>% 
   inner_join(get_sentiments("nrc")) %>% 
  filter(sentiment == "positive") %>% 
  count(word, sort = TRUE)
```

```{r}
   books %>% 
   filter(book == "Sense & Sensibility")  %>% 
   inner_join(get_sentiments("nrc")) %>% 
  filter(sentiment == "negative") %>% 
  count(word, sort = TRUE)
```

